-- Create Synapse User and Database
CREATE USER V_SYNAPSE_POSTGRES_USER WITH PASSWORD 'V_POSTGRES_PASSWORD';
CREATE DATABASE V_SYNAPSE_POSTGRES_DB_NAME OWNER V_SYNAPSE_POSTGRES_USER LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE V_SYNAPSE_POSTGRES_DB_NAME TO V_SYNAPSE_POSTGRES_USER;

\c V_SYNAPSE_POSTGRES_DB_NAME
GRANT ALL ON SCHEMA public TO V_SYNAPSE_POSTGRES_USER;

-- Create MAS (Matrix Authentication Service) User and Database
CREATE USER V_MAS_DATABASE_USERNAME WITH PASSWORD 'V_MAS_DATABASE_PASSWORD';
CREATE DATABASE V_MAS_DATABASE_NAME OWNER V_MAS_DATABASE_USERNAME LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE V_MAS_DATABASE_NAME TO V_MAS_DATABASE_USERNAME;

\c V_MAS_DATABASE_NAME
GRANT ALL ON SCHEMA public TO V_MAS_DATABASE_USERNAME;

-- Create SyncV3 User and Database
CREATE USER V_SYNC_USERNAME WITH PASSWORD 'V_SYNC_PASSWORD';
CREATE DATABASE V_SYNCV3_DB_NAME OWNER V_SYNC_USERNAME LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE V_SYNCV3_DB_NAME TO V_SYNC_USERNAME;

\c V_SYNCV3_DB_NAME
GRANT ALL ON SCHEMA public TO V_SYNC_USERNAME;
